name: issues
on:
  issues:
    types: [closed]
jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Did I solve your problem?
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            I hope we solved your problem.
            
            If you like using Rich, you might also enjoy [Textual](https://textual.textualize.io)
            
